services:
  - type: web
    name: stockfish-api
    env: python
    buildCommand: |
      . /etc/secrets/git_auth.sh
      git submodule update --init --recursive
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000